---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{r include=FALSE}
library(ggplot2)
library(xtable)
```

## Loading and preprocessing the data

```{r echo=TRUE}
data <- read.csv(unz("activity.zip", "activity.csv"), header=TRUE)
```

## What is mean total number of steps taken per day?

```{r echo=TRUE, results='asis'}
df <- aggregate(data$steps, list(data$date), sum, na.rm = TRUE)
names(df) <- c("Date", "Steps")
ggplot(df, aes(x=Steps)) + geom_histogram(binwidth=2000)
xt <- xtable(data.frame(
  mean=mean(df$Steps), 
  median=median(df$Steps),
  row.names="Total Steps (per day)"
))
print(xt, type = "html")
```

## What is the average daily activity pattern?

```{r echo=TRUE}
df <- aggregate(data$steps, list(data$interval), mean, na.rm = TRUE)
names(df) <- c("Interval", "Average.Steps")
ggplot(df, aes(x=Interval, y=Average.Steps)) + geom_line()
```

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
